// DOM SELECTION

/*
-TagName
-byid
-byclassName
-querySelector
-querySelectorAll
-images
-links
-Forms
//  get & set attributes
// 2 method
// innerHTML
// innerText


*/

// let h1=document.getElementsByTagName("h1");
// let h1=document.getElementById("unique");
// let h1=document.getElementsByClassName("cls");

// classlist
// contains


// Create Element
// Dom events
// Form Events
// addeventListener
// formvalidation 

// Bom 
// localstorage
// sessionstorage
// setTimeout
// setInterval
// location


// let my_div=document.createElement("div");
// my_div.classList.add("cls");
// // let text1="hello1";
// let text="hello1 <br/> This text generated by PHP";
// my_div.innerHTML=text

// // my_div.append(text)

// console.log(my_div)


// Click event
// Mouse Event 
// Keyboard event 
// Form Event
// PreventDefault




// button content



// let _alert= document.querySelector(".alert");
// let span_x = document.querySelector(".alert span");

// console.log(span_x)

// let menu=document.createElement("div");
// let menu_ul=document.createElement("ul");
// let menu_li1=document.createElement("li");
// let link=document.createElement("a");
// link.href="https://www.youtube.com";
// link.append("Youtube");

// menu_li1.append(link);
// menu_ul.append(menu_li1)
// menu.append(menu_ul);




// console.log(menu)

// let form = document.forms[0];
// let username= form.username;
// let age = form.age;
// let email=form.email;
// let password=form.password;
// let c_password = form.c_password;
// let check = form.check;

// let test_user = false;
// let test_age = false; 
// let test_email = false;
// let test_c_password = false
// let test_check=false;
// let str_user="";
// let str_age="";
// let str_email="";
// let str_password="";
// let str_check="";

// form.onsubmit=(e)=> {
//     e.preventDefault();
//     if(username.value.length>8 && username.value.length<11){
//         test_user=true
//     }
    







// Form Fields


// setTimeOut


let div_content=document.querySelector(".content")
// setTimeout(function(){
//     div_content.innerHTML="<b style='color:red'>Hello sir</b>"
// },5000);






let input= document.querySelector(".swal2-input");
let btn =document.querySelector(".swal2-confirm");


let counter= document.querySelector(".counter");

let max=5;
// let int=setInterval(()=>{
  
   
//     counter.innerHTML=max
//     max-=1
//     if(max==-1){
//         clearInterval(int)
//     }
// },1000)
// setInterval(()=>{
//     console.log("hello karim");
// },1000)

let a=15;

// let my_interval=setInterval(()=>{
// console.log("hello"+" "+a);
// a--;
// if(a<=10){
//    clearInterval(my_interval) 
// }
// },2000)

let reload =document.querySelector("#btn");
let _close =document.querySelector("#btn2");

// let reload=document.querySelector("button");
// let _close=document.querySelector("#close")
console.log(_close)





// btn2.onclick=()=>{
  
//   let  a=window.open("https://www.youtube.com","","height:500px");
//   btn3.onclick=()=>{
//     a.close();
//    }


// }















